### ISSUE TITLE
Can you add me as maintainer?

### ISSUE THREAD

**Issue by noonsleeper** [flathub/com.visualstudio.code.tool.git-lfs#19]
Since @bbhtt commented me that [the maintainer was inactive](https://github.com/flathub/com.vscodium.codium/pull/276), I want to maintain this, because is a useful tool for codium/code-oss.

**Comment by bbhtt** [comment]
@ranisalt do you have any issue with noonsleeper lending an extra hand? They maintain the vscodium packages on Flathub.


Also I added git-lfs to the SDK yesterday https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/16885 If everything goes well, it will be in freedesktop-sdk 24.08 and you can drop this altogether.

**Comment by ranisalt** [comment]
Not at all, it will be helpful to have another pair of hands with knowledge on it :)

**Comment by bbhtt** [comment]
Invite sent, please accept within a week. Thanks.
